### ISSUE TITLE
Simplify Running the Algorithm out of the Box

### ISSUE THREAD

**Issue by tbr-git** [brucelit/slpn-miner#1]
Hi,

I tested your code and had a few minor problems/ovserved a few small bugs:

- `PM4Py` is missing in the requirements file (the current version 2.7.11.3 works for example)
- I'm not entirely sure how to run it. Some of the files use relative imports which suggests that the `Python` module system is used. However, not all directories contain an `__init__.py`.
- If I provide an SLPN as input for which I want to discover new/better weights, the xml-based exporter will ultimately restore the old weights (after an intermediate update).

**Comment by brucelit** [comment]
Thank you for raising the issues:

- the missing requirements are included now.
- You can run it directly from main.py.
- The problem with the wrong weight during export is solved.
