### ISSUE TITLE
Use of Alignments

### ISSUE THREAD

**Issue by tbr-git** [brucelit/slpn-miner#2]
Hi,

I saw that you internally use alignments to identify fitting traces (with improved performance). 
This should work fine for sound workflow nets where the only deadlock is the final marking.
However, for general Petri nets, some traces might be discarded that end in a deadlock that is not the final marking.
In principle, it should be possible to leverage the product net construction to identify "fitting" traces under SLPN semantics.
Besides, checking for fitness == 1 might not be numerically stable.

**Comment by brucelit** [comment]
Hi, thank you very much for your feedback. The alignments part has been removed. We find fitting traces through cross-product construction.
